### ISSUE TITLE
2 core data packages are not passed pipeline

### ISSUE THREAD

**Issue by Mikanebu** [datahq/assembler#14]
We have 2 core data packages that have not passed pipeline. The problem is `geopoint` type. 
In the first time, it errored with `invalid geopoint type`. Then I fixed both of them. Now we have a different error, probably with `jsontableschema` library. 
* airport-codes - https://github.com/datasets/airport-codes
* smdg-master-terminal-facilities-list - https://github.com/datasets/smdg-master-terminal-facilities-list

Error outcome from pipeline:
```
AttributeError: 'list' object has no attribute 'split'
```

**Comment by zelima** [comment]
@Mikanebu Have you investigated this issue? If you think this is a problem of `jsontableschema` lib, why do we have the issue opened here?

**Comment by Mikanebu** [comment]
@zelima I was not sure that error related with `jsontableschema`, that is why I opened here, since pipeline throws this error

**Comment by zelima** [comment]
INVALID wrong place for this issue
