### ISSUE TITLE
INVALID state for pipelines

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/assembler#25]
If you go and visit http://datahub.io/anuveyatsu/gdp/pipelines, you can see that it has status of INVALID and error:

```
Dirty dependency: Cannot run until all dependencies are executed
Dependency unsuccessful: Cannot run until all dependencies are successfully executed
```

**Comment by akariv** [comment]
@anuveyatsu is this still a problem?
What was the status that you expected to see?

**Comment by anuveyatsu** [comment]
@akariv now it is working for given dataset. However, when I push a dataset, it immediately gets "INVALID" state. But then once all pipelines are passed it changes to "SUCCEEDED". I guess it shouldn't go to "INVALID" state.

**Comment by anuveyatsu** [comment]
@akariv it is still a problem as can be seen here - https://datahub.io/core/country-list - we have that message `We've failed to build your latest changes. Please, see details here.` in the top due to pipelines `state: INVALID`.

**Comment by zelima** [comment]
@anuveyatsu I don't think this is still a case as obsolete. Can we close?

**Comment by anuveyatsu** [comment]
@zelima yes, it is outdated since we reimplemented the assembler

**Comment by zelima** [comment]
FIXED/OBSOLETE
