### ISSUE TITLE
Derived preview resources are too large

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/assembler#27]
Recently, we have implemented generating `derived/preview` resources, which are first 10k rows of the original resource. It was decided to make it in JSON format for convenience in the frontend. However, as we can see now, JSON versions usually are larger in size than CSV versions. E.g., for finance-vix dataset, original resource is `~228KB`, while `derived/preview` version is `~528KB`. It becomes crucial when loading resources that are several MB in sizes.

Another point is we could skip generating `derived/preview` if the number of rows is `<10k` as it does not make a lot of sense or am I missing something? Frontend would use original resource for the preview if `derived/preview` is not found. Notice, that we have to generate preview views anyway.

In addition, we could reduce number of rows for preview resources, e.g., only first 1k rows. Consider https://pkgstore.datahub.io/f512ef8d39ada702fde60efe1ca59c17/farm-url/latest/datapackage.json which has a resource with `4987` rows . What do you think?

**Comment by akariv** [comment]
We can fine-tune the number of rows, 1k rows sounds reasonable to me as well (#32)
As for JSON vs. CSV - generally speaking, if we store/get stuff from S3 in compressed form then it doesn't really matter (the savings would be very small). Need to check on how to do that with S3 (#30)
Lastly, we should skip creating the preview resource in case it's already small (#31).

I opened an issue for each of those tasks.
