### ISSUE TITLE
Bytes property is showing wrong information

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/assembler#28]
If you check this dataset - https://pkgstore.datahub.io/f512ef8d39ada702fde60efe1ca59c17/farm-url/latest/datapackage.json :

* source/tabular resource - `bytes: 51811260`, which is ~52MB but in fact it is ~17MB
* same applies to all versions of resources and dataset itself

**Comment by akariv** [comment]
Should be resolved in https://github.com/frictionlessdata/datapackage-pipelines/commit/0987a5e4adb03072bb6ed80412d408ffc2a7f0ab of `datapackage-pipelines`.
