### ISSUE TITLE
json files end up with ".csv.json" in url

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#3]
After DataSet is published, if you try to download any file in json format you'll get something like this: https://pkgstore-testing.datahub.io/0e9b59cd50f1884058c1aa242d71a228/finance-vix/latest/.datahub/json/data/vix-daily.csv.json

Plus if you try and open the file it is still CSV. 

This also impacts resource paths in `datapackage.json` and crashes graphs and tables
```
...
resources: [{
   name: ...
   path: ".datahub/json/data/vix-daily.csv.json"  
}]
```

**Comment by akariv** [comment]
This was fixed by creating separate resource names for the original and json resources.

**Comment by zelima** [comment]
@akariv link still ends with `.csv.json`. I guess that is expected behaviour as it's valid json for now, correct? 
https://pkgstore-testing.datahub.io/0e9b59cd50f1884058c1aa242d71a228/co2-ppm/latest/.datahub/json/data/co2-mm-mlo.csv.json

**Comment by akariv** [comment]
Yes, we keep the original extension on purpose.
