### ISSUE TITLE
Fine-tune the number of rows needed for preview resources

### ISSUE THREAD

**Issue by akariv** [datahq/assembler#32]
Choose a good number of rows for previewing the data (based on our current core datasets).

**Comment by zelima** [comment]
@anuveyatsu Can you decide on this?

**Comment by anuveyatsu** [comment]
@zelima I think 1k is pretty enough. Do you ever scroll a table with 1k rows to the end? I think even 100 would be OK, but let's do 1k for now and it should improve loading speed of some large datasets.

**Comment by zelima** [comment]
Hm... this makes me think about how we are going to deal with sorting data that is time sensitive. Eg: for Finance Vix, that is updated daily, we need last 1000 rows (or maybe first for other datasets), to display the latest data

**Comment by zelima** [comment]
FIXED. As discussed in person we reduced it till 200. Followup showing first/last part of dataset here #39

**Comment by zelima** [comment]
This is back to 10,000 now, as suggested by @rufuspollock
