### ISSUE TITLE
Processing excel files with type integer fails validation

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#87]
Originally comes from here https://github.com/datahq/datahub-qa/issues/119

Pushing following excel files [xls](https://github.com/frictionlessdata/test-data/raw/master/files/excel/sample-1-sheet.xls) and [xlxs](https://github.com/frictionlessdata/test-data/raw/master/files/excel/sample-1-sheet.xlsx) results with validation erros (see analysis section).  

## Acceptance Criteria

* [ ] able to publish both files without problem

## Tasks

* [x] Do analysis
* [ ] fix

## Analysis 

publishing above files will result with following validation errors: 

xlx:
![image](https://user-images.githubusercontent.com/15143785/36308253-37a88c6c-1339-11e8-8255-cbc96064df88.png)

xlsx:
![image](https://user-images.githubusercontent.com/15143785/36308281-61c1a7ae-1339-11e8-9ba1-9f61e2ee9d64.png)

## Reason

This is happening cause the field types guessed with `infer` method in `datahub-client`, is not in harmony with the `tabulator.Stream` method. While infer method is guessing types correctly, tabulator transforms integers into numbers (and booleans into integers if `xls`) if the source is excel leading in errors while casting fields values according to Schema. 

## Possible solutions

1. [Get rid of `infer` method](https://github.com/datahq/datahub-client/blob/master/lib/utils/datahub.js#L395) in `datahub-client` and allow python library to take care of it

While this seems the solution and data is processed without any problem - field types are not actually inferred and are forced to be set to `strings`, see https://github.com/frictionlessdata/datapackage-pipelines/blob/master/datapackage_pipelines/lib/stream_remote_resources.py#L181-L188
I suppose this is happening cause infer method of [tableschema-py](https://github.com/frictionlessdata/tableschema-py) library, is not as good at guessing field types as [tablechema-js](https://github.com/frictionlessdata/tabulator-py) for excel files. Take a look at this issue https://github.com/frictionlessdata/tabulator-py/issues/230

2. Fix the Stream method in tabulator (if that is an issue at all for them). https://github.com/frictionlessdata/tabulator-py/issues/230 and do not transform integer field values into a numbers/ booleans -> integers

3. All together: I think best place to infer schema is the place where Streaming is happening. So think best solution here would be 
3.1 Get rid of infer method in `datahub-client`
3.2 Fix theStream method in tabulator
3.3 Fix the infer method in tablschema-py for excel files

**Comment by akariv** [comment]
@zelima 
I'm not sure which Python library will take care of inferring the types instead of datahub-client. Where is `tableschema-py`'s `infer` being used in this flow?
If I understand correctly, there's a mismatch between `tableschema-js` (which infers some values) and `tabulator` (which reads these values with different types). One of these needs to be patched to resolve the issue. Which one exactly needs to be discussed with the frictionless data team - I suggest we open matching issues in the FD repos (for tabulator and tableschema-js) and also start a discussion in the gitter channel.

**Comment by zelima** [comment]
@akariv 
> 'm not sure which Python library will take care of inferring the types instead of datahub-client. Where is tableschema-py's infer being used in this flow?

Nowhere, filed types are forced to [be strings](https://github.com/frictionlessdata/datapackage-pipelines/blob/master/datapackage_pipelines/lib/stream_remote_resources.py#L181-L188). Just thought we could use infer method there, instead of forcing them to be strings.

> If I understand correctly, there's a mismatch between tableschema-js (which infers some values) and tabulator 

Yes, correct

> Which one exactly needs to be discussed with the frictionless data team

I think `tablaeschema-js` is working fine in this case, as the types are guessed correctly. I've already opened issue for tabulator here https://github.com/frictionlessdata/tabulator-py/issues/230

**Comment by zelima** [comment]
Ok so diving deeply into this I've got the following:

> Excel treats all numbers as floats. In general, it doesn't care whether your_number % 1 == 0.0 is true or not. 
https://stackoverflow.com/a/8826770/6056362

Also, similar problem with [openpyxl used by tabulator](https://github.com/frictionlessdata/tabulator-py/blob/master/tabulator/parsers/xlsx.py#L9) to parse `.xlsx` data
>iter_worksheet casts all numeric values as floats.
https://bitbucket.org/openpyxl/openpyxl/issues/131/incorect-reading-integer-in-use_iterators#comment-10399143

Meaning that any number coming from Excel is `float` and python parses it as `float`, So when `stream_remote_resources` complains `can't cast value "1.0" for type "integer" ` it actually complains correctly.

On the other hand we have `XLSX` library from NPM used in CLI to infer a schema for later use. `XLSX` library treats number got from excel as JS number (`Number(n)`) https://www.npmjs.com/package/xlsx#data-types

Playing around a bit with JS number I've got the following: 

```
let a = Number(1)
let b = Number(1.0)

console.log('Number(1)='+a, '|', 'Number(1.0)='+b)
>>> Number(1)=1 | Number(1.0)=1
console.log(a === b)
>>> true
console.log(a == b)
>>> true
```

In any case `Number(n)` returns "number". Meaning when [data.js reads Excel workbook](https://github.com/datahq/data.js/blob/master/lib/parser/xlsx.js#L9) used in [datahub-client](https://github.com/datahq/datahub-client/blob/master/lib/utils/datahub.js#L425) it gets list of JS numbers. That list of rows (**and not path to the file or file buffer**) is later used to infer [schema by tableschema-js](https://github.com/frictionlessdata/tableschema-js/blob/master/src/table.js#L190), Leaving us with `type: number` if there is not at least one actual float Eg `1.1`

So Think if even the excel file would like this
```
one,two,three
1.0,2.0,3.0
4.0,5.0,6.0
...
```
We would infer the same exact schema. (Not sure how CSV parser works when it detects correctly) 

As a solution, I suggest forcing type `integer` to `number` if data is xls(x) somewhere here https://github.com/datahq/datahub-client/blob/master/lib/utils/datahub.js#L429

**Comment by zelima** [comment]
FIXED in https://github.com/frictionlessdata/tabulator-py/commit/9675ead99fff26b9c5cdf64831f01bf3f9c2df39
